services:
  techcast-api:
    build: .
    ports:
      - "3100:3100"
    volumes:
      # Montar diretório de saída para persistir dados
      - ./output:/app/output
      # Montar arquivo .env para facilitar configuração
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - CRON_TIMEZONE=America/Sao_Paulo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 